#!/usr/bin/python

import os
import sys
import errno
import eduid_IdP_html


def mkdir_p(path, mode=0755):
    try:
        os.makedirs(path, mode)
    except OSError as exc:
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else:
            raise

if len(sys.argv) != 2:
    sys.stderr.write("Syntax: {!s} output-dir\n".format(sys.argv[0]))
    sys.exit(1)

output_dir = sys.argv[1]

mkdir_p(output_dir)

# Run eduid_IdP_html.main() to generate all translated HTMLs in the build process
assert(eduid_IdP_html.main(
    verbose=True, output_dir=output_dir)
)